version: '3.8'
services:
  database:
    container_name: mern-starter-database-dev
    image: mongo:latest
    restart: unless-stopped
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    environment:
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_DATABASE: ${MONGO_DATABASE}
    volumes:
      - ./database/init.sh:/docker-entrypoint-initdb.d/init.sh

  api:
    container_name: mern-starter-api-dev
    image: mern-starter-api-dev
    restart: unless-stopped
    build:
      context: ./
      dockerfile: packages/api/config/Dockerfile.dev
      args:
        PORT: ${API_PORT}
        PORT_DEBUGGER: ${API_PORT_DEBUGGER}
    depends_on:
      - database
    ports:
      - ${API_PORT}:${API_PORT}
      - ${API_PORT_DEBUGGER}:${API_PORT_DEBUGGER}
    volumes:
      - ./packages/api:/user/app/packages/api
      - ./packages/types:/user/app/packages/types
      - ./packages/validators:/user/app/packages/validators
      - ./packages/locales:/user/app/packages/locales
    command: yarn watch:api
    environment:
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_DATABASE: ${MONGO_DATABASE}
      MONGO_URL: ${MONGO_URL}
      PORT: ${API_PORT}

  client:
    container_name: mern-starter-client-dev
    image: mern-starter-client-dev
    restart: unless-stopped
    build:
      context: ./
      dockerfile: packages/client/config/Dockerfile.dev
      args:
        PORT: ${CLIENT_PORT}
    depends_on:
      - database
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    volumes:
      - ./packages/client:/user/app/packages/client
      - ./packages/types:/user/app/packages/types
      - ./packages/validators:/user/app/packages/validators
      - ./packages/locales:/user/app/packages/locales
    command: yarn watch:client
    environment:
      REACT_APP_PORT: ${CLIENT_PORT}
      REACT_APP_API_PORT: ${API_PORT}
      REACT_APP_API_URL: ${API_URL}
